---

- name: Download EPEL GPG key
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    owner: root
    group: root
    mode: 0444
  become: yes

- name: Ensure EL GPG key is added to rpm database
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    state: present

- name: Download EPEL Repository
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/7/x86_64
    dest: /var/www/html/yum/epel/7/x86_64
    owner: root
    group: root
    mode: 0755
  become: yes
