---

- name: Import Installation tasks for CentOS
  import_tasks: redhat.yml
  when: ansible_distribution|lower == 'centos'

- name: Import Download EPEL tasks
  import_tasks: "download-epel.yml"
  when: download_epel

# Create a more generalized download repo task file?
- name: Import Download EL tasks
  import_tasks: "download-el.yml"
  when: download_el