---

#- name: Setup local repositories
  # Set repos in /mnt/repos

- name: Install httpd
  yum:
    name: "httpd"
    state: "present"
  become: true

- name: Create dir
  file:
    path: /var/www/html/pub
    state: directory
    owner: apache
    group: apache
    mode: 0777
  become: true

- name: Get repository file (Workaround for recursive remote copying)
  command: "find /mnt/repo -type f"
  register: files_to_copy

- name: Setup repositories for remote connections
  copy:
    src: "{{ item }}"
    dest: /var/www/html/pub
    owner: apache
    group: apache
    mode: 0755
    remote_src: true
  with_items:
  - "{{ files_to_copy.stdout_lines }}"
  become: true

- name: Set correct file permissions
  file:
    path: /var/www/html/pub
    state: directory
    recurse: true
    mode: 0644
    owner: apache
    group: apache
  become: true

- name: Ensure httpd is restarted
  service:
    name: httpd
    state: restarted
  become: true

- name: Ensure firewall is opened
  firewalld:
    service: http
    permanent: true
    state: enabled
  become: true


