---

- name: Install packages
  yum:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
  - httpd
  - yum-utils

- name: Ensure httpd is restarted
  service:
    name: httpd
    state: restarted
  become: true

- name: Ensure firewall is opened
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  become: true
  with_items:
  - http
  - https


