---

- name: Setup local repositories
  # Set repos in /mnt/repos

- name: Install httpd
  yum:
    name: "httpd"
    state: "present"
  become: true

- name: Setup repositories for remote connections
  # Copy from repository_local_path to httpd /var/www/html/

- name: Ensure httpd is started
  service:
    name: httpd
    state: restarted
  become: true

- name: Ensure firewall is opened



